// Generate data/stanford/grad-programs.yaml from the bulletin scrape cache:
// each program keeps only the courses that exist in classes.yaml, and programs
// with fewer than 2 mapped classes are left in the cache for future curation.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import * as yaml from "js-yaml";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const cache = JSON.parse(fs.readFileSync(path.join(root, "data/stanford/bulletin-programs-cache.json")));
const { classes } = yaml.load(fs.readFileSync(path.join(root, "data/stanford/classes.yaml"), "utf8"));
const known = new Set(classes.map((c) => c.id));

const DEPT = {
  AA: "Aeronautics and Astronautics", APLPH: "Applied Physics",
  AEPHY: "Applied and Engineering Physics", BMDS: "Biomedical Data Science",
  BMP: "Biomedical Physics", BIOPH: "Biophysics", CHEME: "Chemical Engineering",
  CEE: "Civil and Environmental Engineering", CME: "Computational and Mathematical Engineering",
  CS: "Computer Science", DESIGN: "Design", EE: "Electrical Engineering",
  ENERGY: "Energy Science and Engineering", ENGR: "Engineering", LING: "Linguistics",
  MATSC: "Materials Science and Engineering", MATH: "Mathematics",
  ME: "Mechanical Engineering", MGTSC: "Management Science and Engineering",
  MUSIC: "Music", PHYS: "Physics", SYMBO: "Symbolic Systems",
};
const DESIG = { MS: ["MS", "ms"], PHD: ["PhD", "phd"], ENG: ["Engineer", "eng"], PMN: ["PhD Minor", "phd-minor"], MA: ["MA", "ma"] };

const out = [];
for (const p of cache) {
  if (p.error) continue;
  const [dept, suffix] = [p.code.replace(/-[A-Z]+$/, ""), p.code.match(/[A-Z]+$/)[0]];
  const mapped = (p.courses ?? []).filter((c) => known.has(c));
  if (mapped.length < 2) continue;
  const [label, type] = DESIG[suffix];
  out.push({
    id: p.code.toLowerCase(),
    name: `${DEPT[dept]} (${label})`,
    type,
    classes: mapped,
  });
}
out.sort((a, b) => a.name.localeCompare(b.name));

const header = `# Stanford graduate programs -> classes, AUTO-GENERATED by
# tools/gen_grad_programs.mjs from the bulletin scrape (2026-09-01).
# Only bulletin-cited courses that exist in classes.yaml appear here; the full
# per-program course lists live in bulletin-programs-cache.json. Programs whose
# bulletin pages cite fewer than 2 mapped classes are omitted (many defer
# requirements to department documents).
`;
fs.writeFileSync(
  path.join(root, "data/stanford/grad-programs.yaml"),
  header + yaml.dump({ programs: out }, { lineWidth: 100 })
);
console.log(`${out.length} programs written:`);
for (const p of out) console.log(` ${p.id.padEnd(11)} ${p.classes.length} classes: ${p.classes.join(", ")}`);
